Implements actions-ecosystem

diff --git a/.github/workflows/pr_draft.yml b/.github/workflows/pr_draft.yml
--- a/.github/workflows/pr_draft.yml
+++ b/.github/workflows/pr_draft.yml
@@ -1,11 +1,43 @@
-name: Label Draft PRs
+name: PR Draft
 
 on:
-  pull_request_target:
-    types: [opened, ready_for_review, converted_to_draft]
+  pull_request:
+    types:
+      [
+        edited,
+        opened,
+        reopened,
+        synchronize,
+        converted_to_draft,
+        ready_for_review,
+      ]
 
+permissions:
+  contents: read
+  pull-requests: write
 jobs:
-  label-draft:
+  pr-draft:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Check PR Title
+        run: |
+          if [[ "${{ github.event.pull_request.title }}" =~ ^[a-zA-Z]+-[0-9]+ ]]; then
+            echo "PR title is valid."
+          else
+            echo "PR title is invalid. Please use the format <JIRA-TICKET>: <Title>"
+            exit 1
+          fi
+
+      - name: Check PR Description
+        run: |
+          if [ -z "${{ github.event.pull_request.body }}" ]; then
+            echo "PR description is empty. Please provide a description."
+            exit 1
+          fi
+  add-label-draft:
     runs-on: ubuntu-latest
     if: github.event.pull_request.draft == true
     steps:
@@ -17,14 +49,13 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: DO NOT MERGE
-
   remove-label-draft:
     runs-on: ubuntu-latest
     if: github.event.pull_request.draft == false
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-        
+
       - name: Remove label from PR
         uses: actions-ecosystem/action-remove-labels@v1.3.0
         with:
