Fixed Regex Rule from Get version from tag. Support only v#.#.#

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -38,24 +38,21 @@ jobs:
       - name: Get version from tag
         id: get_version
         run: |
-          if [[ $GITHUB_REF == refs/tags/* ]]; then
-            VERSION=${GITHUB_REF#refs/tags/}
-            VERSION=${VERSION#v}
-            echo "version=$VERSION"
+          set -e
+          if [[ $GITHUB_REF == */releases/tag/v* ]]; then
+            VERSION=${GITHUB_REF##*/releases/tag/v}
           else
-            echo "GIT REF is not a tag"
-            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
-            VERSION=${VERSION#v}
-            echo "version=$VERSION"
-          fi
-
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?(rc[0-9]+)?$ ]]; then
-            echo "version=$VERSION"
-            echo "Error: No version found"
+            echo "Error: GITHUB_REF is not a valid tag format"
             exit 1
           fi
 
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$ ]]; then
+            echo "Error: Invalid version format ($VERSION)"
+            exit 1
+          fi
+
+          echo "version=$VERSION" >> $GITHUB_ENV
+          echo "VERSION detected: $VERSION"
 
       - name: Repository Setup
         run: |
