Fixed Regex Rule from Get version from tag. Support v#.#.# or #.#.#

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -39,20 +39,20 @@ jobs:
         id: get_version
         run: |
           if [[ $GITHUB_REF == refs/tags/* ]]; then
-              VERSION=${GITHUB_REF#refs/tags/}
-              VERSION=${VERSION#v}
-              echo "version=$VERSION" 
+            VERSION=${GITHUB_REF#refs/tags/}
+            VERSION=${VERSION#v}
+            echo "version=$VERSION"
           else
-              echo "GIT REF is not a tag"
-              VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
-              VERSION=${VERSION#v}
-              echo "version=$VERSION"
+            echo "GIT REF is not a tag"
+            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
+            VERSION=${VERSION#v}
+            echo "version=$VERSION"
           fi
 
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$ ]]; then
-              echo "version=$VERSION"
-              echo "Error: No version found"
-              exit 1
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?(rc[0-9]+)?$ ]]; then
+            echo "version=$VERSION"
+            echo "Error: No version found"
+            exit 1
           fi
 
           echo "version=$VERSION" >> $GITHUB_OUTPUT
